name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          active_profiles: >
            [
              "github"
            ]
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/NFT-Lab/*",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${{ secrets.DEPLOY_USERNAME }}",
                "password": "${{ secrets.DEPLOY_ACCESS_TOKEN }}"
              }
            ]
          
      - uses: actions/checkout@v2
        with:
          repository: Hotmoka/Hotmoka
          ref: '1.0.0'
          path: './hotmoka'
          
      - name: Install Hotmoka
        run: |
          mvn install -f ./hotmoka/pom.xml --projects io-hotmoka-takamaka    
      
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
